version: '3'

services: 
  mock-server:
    image: nginx:1.16.0-alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/response:/var/www/data/response
    ports:
      - "8080:80"

